import Link from 'next/link'

import '@/styles/global.css'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>Xablau</header>
        
        <Link href={'/'} shallow>Home</Link>

        <Link href={'/dashboard'} shallow>Dashboard</Link>
        
        {children}
        
        <footer>Feito com muito amor</footer>
      </body>
    </html>
  )
}
